services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    networks:
      - devops-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://13.223.48.211:5000
    ports:
      - "80:3000"
    networks:
      - devops-network
    depends_on:
      - backend

networks:
  devops-network:
    driver: bridge
